version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: dungkar_dzong_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dungkar
      POSTGRES_PASSWORD: dungkar_secret
      POSTGRES_DB: dungkar_dzong_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dungkar_dzong_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  postgres_data: 