version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: dungkar_dzong_db
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: dungkar
      POSTGRES_PASSWORD: dungkar_secret
      POSTGRES_DB: dungkar_dzong_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dungkar_dzong_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://dungkar:dungkar_secret@postgres:5432/dungkar_dzong_db"
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes:
  postgres_data: 