name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          ssh $VPS_USER@$VPS_HOST 'bash -s' << 'ENDSSH'
            cd ~/dungkar-dzong-maintenance
            
            # Ensure Traefik directories exist
            mkdir -p traefik/config
            touch traefik/acme.json
            chmod 600 traefik/acme.json
            
            # Pull latest changes
            git pull
            
            # Copy Traefik config
            cp traefik/config/tls.yml traefik/config/
            
            # Restart containers
            docker compose down
            docker compose up -d --build
            
            # Run migrations
            sleep 10  # Wait for containers to be ready
            docker compose exec -T app yarn prisma migrate deploy
            
            # Check deployment status
            docker compose ps
            echo "Deployment completed. Check logs with: docker compose logs -f"
          ENDSSH
