name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          ssh $VPS_USER@$VPS_HOST 'bash -s' << 'ENDSSH'
            # Exit on any error
            set -e

            echo "Starting deployment..."
            cd ~/dungkar-dzong-maintenance || exit 1
            
            echo "Setting up directories..."
            # Ensure required directories exist with correct permissions
            sudo mkdir -p /etc/traefik/config /var/www/dungkar-dzong/uploads || exit 1
            sudo chown -R $USER:$USER /etc/traefik /var/www/dungkar-dzong || exit 1
            sudo chmod 600 /etc/traefik/acme.json || exit 1
            sudo chmod 755 /var/www/dungkar-dzong/uploads || exit 1
            
            echo "Copying Traefik config..."
            # Copy Traefik config
            sudo cp traefik/config/tls.yml /etc/traefik/config/ || exit 1
            
            echo "Pulling latest changes..."
            # Pull latest changes
            git pull || {
              echo "Git pull failed. Please resolve conflicts manually."
              exit 1
            }
            
            echo "Loading environment variables..."
            # Load environment variables
            set -a
            source .env || exit 1
            set +a
            
            echo "Restarting containers..."
            # Restart containers with environment loaded
            docker compose down || exit 1
            docker compose up -d --build || exit 1
            
            echo "Running database migrations..."
            # Run migrations
            sleep 10  # Wait for containers to be ready
            docker compose exec -T app yarn prisma migrate deploy || exit 1
            
            echo "Checking deployment status..."
            # Check deployment status
            docker compose ps
            echo "Deployment completed successfully!"
          ENDSSH
